services:
  - type: web
    name: myblog
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn myblog.wsgi:application"
    envVars:
      - key: SECRET_KEY
        value: your-secret-key
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: django-vibingnew.onrender.com